import base64
import json
from pathlib import Path
import tempfile
import unittest
import urllib.error
import urllib.request
import uuid as uuid_module
from urllib.parse import parse_qs, urlparse

from server import RixPanelServer


class AutoDefaultDomainTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.server = RixPanelServer(self.temp_dir.name)
        self.server.start()

    def tearDown(self):
        self.server.stop()
        self.temp_dir.cleanup()

    def post(self, payload, headers=None):
        request_headers = {"Content-Type": "application/json"}
        request_headers.update(headers or {})
        request = urllib.request.Request(
            self.server.base_url + "/api/v1/configs/generate",
            data=json.dumps(payload).encode("utf-8"),
            headers=request_headers,
            method="POST",
        )
        try:
            response = urllib.request.urlopen(request, timeout=3)
        except urllib.error.HTTPError as exc:
            response = exc
        return response.status, json.loads(response.read())

    def test_domain_only_payload_autofills_server_sni_host_and_uuid(self):
        status, body = self.post({"name": "خودکار", "domain": "panel.example.org"})

        self.assertEqual(status, 201)
        self.assertEqual(body["server"], "panel.example.org")
        self.assertEqual(body["sni"], "panel.example.org")
        self.assertEqual(body["host"], "panel.example.org")
        self.assertEqual(body["port"], 443)
        self.assertEqual(body["path"], "/rix-ws")
        self.assertTrue(body["tls"])
        uuid_module.UUID(body["uuid"])
        self.assertIn("@panel.example.org:443", body["vless_uri"])

    def test_domain_only_payload_autofills_name(self):
        status, body = self.post({"domain": "panel.example.org"})

        self.assertEqual(status, 201)
        self.assertEqual(body["name"], "RixPanel Config")

    def test_domain_is_normalized_and_url_is_rejected(self):
        status, body = self.post({"name": "نامعتبر", "domain": "https://panel.example.org"})

        self.assertEqual(status, 422)
        self.assertIn("domain", body["message"])

    def test_domain_with_path_is_rejected(self):
        status, body = self.post({"name": "نامعتبر", "domain": "panel.example.org/evil"})

        self.assertEqual(status, 422)
        self.assertIn("domain", body["message"])

    def test_domain_with_control_character_is_rejected(self):
        status, body = self.post({"domain": "panel.example.org\r\nX-Test: bad"})

        self.assertEqual(status, 422)
        self.assertIn("domain", body["message"])

    def test_ui_uses_browser_hostname_without_manual_host_sni_fields(self):
        root = Path(__file__).resolve().parent
        html = (root / "index.html").read_text("utf-8")
        javascript = (root / "app.js").read_text("utf-8")

        self.assertIn('name="domain"', html)
        self.assertIn("readonly", html)
        self.assertIn("window.location.hostname", javascript)
        self.assertNotIn('name="name"', html)
        self.assertNotIn('name="tls"', html)
        self.assertNotIn('name="remark"', html)
        self.assertNotIn('name="sni"', html)
        self.assertNotIn('name="host"', html)
        self.assertNotIn('name="uuid"', html)

    def test_host_header_is_used_when_domain_is_omitted(self):
        status, body = self.post(
            {"name": "پنل"},
            headers={"Host": "panel.example.org"},
        )

        self.assertEqual(status, 201)
        self.assertEqual(body["server"], "panel.example.org")
        self.assertEqual(body["sni"], "panel.example.org")
        self.assertEqual(body["host"], "panel.example.org")

    def test_forwarded_host_selects_public_domain_for_autogenerated_values(self):
        status, body = self.post(
            {"name": "پراکسی"},
            headers={"X-Forwarded-Host": "rix.example.org", "X-Forwarded-Proto": "https"},
        )

        self.assertEqual(status, 201)
        self.assertEqual(body["server"], "rix.example.org")
        self.assertEqual(body["sni"], "rix.example.org")
        self.assertEqual(body["host"], "rix.example.org")
        self.assertIn("@rix.example.org:443", body["vless_uri"])

    def test_generated_subscription_decodes_to_generated_uri(self):
        status, body = self.post({"name": "خودکار", "domain": "panel.example.org"})

        self.assertEqual(status, 201)
        self.assertEqual(
            base64.b64decode(body["subscription_base64"], validate=True).decode(),
            body["vless_uri"] + "\n",
        )
        parsed = urlparse(body["vless_uri"])
        self.assertEqual(parse_qs(parsed.query)["sni"], ["panel.example.org"])


if __name__ == "__main__":
    unittest.main()
